title: Bioinformatics codes and material
author: Martina Cardinali
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The site contains the material used and developed during the lessons of the MSc in Bioinformatics.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
